name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
  - cron: 0 0 * * 1       # Weekly on Monday at 00:00 UTC

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    name: Linux py ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Check style
        run: pre-commit run --all-files

      - name: Run tests
        run: pytest tests/